spring.application.name=buddaroad01

# Oracle Database Connection Settings
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XEPDB1)))
# DB
spring.datasource.username=BUDDHAROAD_DEV
spring.datasource.password=test250630
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# JPA Settings
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# JWT
jwt.secret-key=a0e6d7e0444442f28fbba9a72e4b2594fae6804e9ead43f0bd8fdaad084a7f1a
jwt.expiration-time=3600000

# Server Port
server.port=8080

#File Upload
spring.servlet.multipart.enabled=true

spring.servlet.multipart.location=C:/IntelliJ/WS/BuddhaRoad/uploads

spring.servlet.multipart.max-file-size=100MB

spring.servlet.multipart.max-request-size=1000MB

com.buddharoad.upload.path=C:/IntelliJ/WS/BuddhaRoad/uploads

#Debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.com.buddharoad=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
